//! Anchor program that exposes Marinade Finance liquid staking through CPI:
//! deposit SOL for mSOL, liquid unstake, delayed unstake, and ticket claims.
//!
//! The program never takes custody. Every instruction forwards the caller's
//! accounts to Marinade after validating the Marinade addresses it depends on.

// Both allows cover code generated by Anchor 0.31.1 macros: `unexpected_cfgs`
// for its feature gates, `deprecated` for its use of `AccountInfo::realloc`.
#![allow(unexpected_cfgs, deprecated)]

use anchor_lang::prelude::*;

pub mod constants;
pub mod error;
pub mod instructions;

use instructions::*;

declare_id!("Bfjb9g895pAyGfuFGgkf1JcUzDeKdxYk2sDJC76RZ89r");

#[program]
pub mod marinade_integration {
    use super::*;

    /// Stakes `lamports` SOL with Marinade and mints mSOL to the caller's
    /// associated token account, creating it if needed.
    pub fn deposit(ctx: Context<DepositSol>, lamports: u64) -> Result<()> {
        ctx.accounts.process(lamports)
    }

    /// Swaps `msol_amount` mSOL for SOL through Marinade's liquidity pool.
    /// Settles immediately and pays the pool fee.
    pub fn liquid_unstake(ctx: Context<LiquidUnstakeSol>, msol_amount: u64) -> Result<()> {
        ctx.accounts.process(msol_amount)
    }

    /// Burns `msol_amount` mSOL and opens a Marinade unstake ticket at the PDA
    /// `["ticket", state, authority, ticket_id]`. Claimable after the epoch ends.
    /// `ticket_id` is consumed by the account constraints as a PDA seed.
    #[allow(unused_variables)]
    pub fn order_unstake(
        ctx: Context<OrderUnstakeSol>,
        msol_amount: u64,
        ticket_id: u64,
    ) -> Result<()> {
        ctx.accounts.process(msol_amount)
    }

    /// Claims the SOL held by a matured unstake ticket to its beneficiary.
    /// `ticket_id` is consumed by the account constraints as a PDA seed.
    #[allow(unused_variables)]
    pub fn claim(ctx: Context<ClaimSol>, ticket_id: u64) -> Result<()> {
        ctx.accounts.process()
    }
}
